GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content" : "VS CODE REST CLIENT",
    "important" : false,
    "user" : "61aef1fca5acc8322c649847"
}

### no content
POST http://localhost:3001/api/notes
Content-type: application/json

{
    
    "important" : false
}

###Send a get request with id that exist
GET http://localhost:3001/api/notes/61919ce8d659380546d7c804

###
DELETE http://localhost:3001/api/notes/6192cef663861cb1c587ccfb

###
PUT http://localhost:3001/api/notes/61919ce8d659380546d7c804
Content-Type: application/json

{
    "content" : "HTML is Easy",
    "important" : false
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "notes": [],
    "username": "shugz",
    "name": "Superuser",
    "password": "salainen"
}